# Generated by Django 4.2.25 on 2025-10-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('season', 'Season')], max_length=10)),
                ('period_identifier', models.CharField(max_length=50)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='companies.company')),
            ],
            options={
                'ordering': ['-total_points', 'user__username'],
            },
        ),
    ]
