# Generated by Django 4.2.25 on 2025-10-08 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rankings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['company', 'period', 'period_identifier', '-total_points'], name='rankings_ra_company_20c504_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together={('user', 'company', 'period', 'period_identifier')},
        ),
    ]
