# Generated by Django 4.2.25 on 2025-10-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('premier_league', 'Premier League'), ('la_liga', 'La Liga'), ('bundesliga', 'Bundesliga'), ('serie_a', 'Serie A'), ('ligue_1', 'Ligue 1'), ('ekstraklasa', 'Ekstraklasa')], max_length=100, unique=True)),
                ('api_football_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'season')},
            },
        ),
    ]
