# Generated by Django 4.2.25 on 2025-10-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('premier_league', 'Premier League (England)'), ('la_liga', 'La Liga (Spain)'), ('bundesliga', 'Bundesliga (Germany)'), ('serie_a', 'Serie A (Italy)'), ('ligue_1', 'Ligue 1 (France)'), ('ekstraklasa', 'Ekstraklasa (Poland)')], max_length=50, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('api_id', models.IntegerField(help_text='League ID from API-Football', unique=True)),
                ('current_season', models.IntegerField(help_text='Current season year')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'leagues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('api_id', models.IntegerField(help_text='Team ID from API-Football', unique=True)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='Match ID from API-Football', unique=True)),
                ('start_time', models.DateTimeField()),
                ('round', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PLAY', 'In Play'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.league')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['league', 'start_time'], name='matches_league__e26e7d_idx'), models.Index(fields=['status', 'start_time'], name='matches_status_14743d_idx')],
            },
        ),
    ]
