# Generated by Django 4.2.25 on 2025-10-08 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_score_points', models.IntegerField(default=3)),
                ('correct_outcome_points', models.IntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'Scoring Configuration',
                'verbose_name_plural': 'Scoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='CompanyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leagues', to='companies.company')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_companies', to='leagues.league')),
            ],
            options={
                'ordering': ['company', 'league'],
                'unique_together': {('company', 'league')},
            },
        ),
    ]
