# Generated by Django 4.2.25 on 2025-10-07 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('points_correct_score', models.IntegerField(default=3, help_text='Points for predicting exact score', validators=[django.core.validators.MinValueValidator(0)])),
                ('points_correct_outcome', models.IntegerField(default=1, help_text='Points for predicting correct winner/draw', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leagues', to='companies.company')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leagues', to='matches.league')),
            ],
            options={
                'db_table': 'company_leagues',
                'ordering': ['company', 'league'],
                'unique_together': {('company', 'league')},
            },
        ),
    ]
