# Generated by Django 5.2.7 on 2025-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('root_admin', 'Root Admin'), ('client_admin', 'Client Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
